language: node_js
node_js: '10'

cache:
  - yarn

before_install:
  - yarn

script:
  - yarn build

deploy:
  provider: pages
  local_dir: dist
  target_branch: gh-pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
